### ISSUE TITLE
Document Python 2/Python 3 support

### ISSUE THREAD

**Issue by jcea** [rohe/pyjwkest#13]
Please, in PYPI, document what versions of Python this project supports:

https://pypi.python.org/pypi/pyjwkest/0.5.1

I am interested in Python 3 support :-p

**Comment by allan-simon** [comment]
+1

**Comment by rohe** [comment]
> 26 nov 2014 kl. 01:17 skrev jcea <notifications@github.com>:
> 
> Please, in PYPI, document what versions of Python this project supports:
> 
> https://pypi.python.org/pypi/pyjwkest/0.5.1
> 
> I am interested in Python 3 support :-p

It’s verified to work with 2.7 and 3.4.2/3.5 .
Development is now done using 3.5 and we use Travis to verify that pyjwkest continues to work with 2.7 .

— Roland
'Look, that's why there's rules, understand? So that you think before you break ’em.’ - Terry Pratchett

**Comment by allan-simon** [comment]
great thanks, so I think the issue can be closed so that not to confuse people ?

**Comment by jcea** [comment]
Please, add "Python 3.5" descriptor in PyPI :-)

https://pypi.python.org/pypi/pyjwkest/

**Comment by rohe** [comment]
> 4 dec 2015 kl. 23:56 skrev jcea <notifications@github.com>:
> 
> Please, add "Python 3.5" descriptor in PyPI :-)
> 
> https://pypi.python.org/pypi/pyjwkest/

Will do !

— Roland
'Look, that's why there's rules, understand? So that you think before you break ’em.’ - Terry Pratchett
