### ISSUE TITLE
Python3 ETA

### ISSUE THREAD

**Issue by DavidHwu** [rohe/pyjwkest#17]
I see that the Python3 implementation is in the works... is there an ETA for this?
Other packages such as https://github.com/rohe/pyoidc is depending on your package to be python 3 ready.

Thanks

**Comment by rohe** [comment]
> 19 feb 2015 kl. 23:55 skrev Bluevalor <notifications@github.com>:
> 
> I see that the Python3 implementation is in the works… is there an ETA for this?

Same as for pyoidc, hopefully in May.

> Other packages such as https://github.com/rohe/pyoidc is depending on your package to be python 3 ready.

I do know that, being responsible for both.

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by DavidHwu** [comment]
Thanks Roland!

Sent from my iPhone

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire
