### ISSUE TITLE
Cannot encrypt JWE with RSA encryption keys that have a kid (keyId)

### ISSUE THREAD

**Issue by arjunsharma** [rohe/pyjwkest#28]
When I follow the example code for creating a JWE, it does not work when I add a "kid" to the encryption key.

Here's what happens when I follow the example as written:

```
>>> encryption_keys = [RSAKey(use="enc", key=RSA.generate(2048))]
>>> jwe = JWE("some content", alg="RSA-OAEP", enc="A256CBC-HS512")
>>> jwe.encrypt(keys=encryption_keys)
'eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkEyNTZDQkMtSFM1MTIifQ.LnOxoMXW_W96Kg51ccpoMDTaHzL1Owky4JCo1zNzZSPZrKWSbil_4DEdOrGPE9Tv3TMNunfJnN0pcB5fu8zXCvoVVUHwshrgIA9mOlHkfkb-4Xq4jOFfemMTpuW-uJhL2wzXa2FvRv96ZpRTEZaC0iYcKJya9aJ0WZOm3hibj1xRJd-ORLEYEjNJco8o5EqGZj4mcT8OaODLvOuqEuq3Bc01S8OORZ5MjUWvjVkc0co5ZmnPyKXvsMhdaT60e2xAzcoQJblhuRJY0j85zqz9IIkufAVFdVieExK-zZRasZ9xvVleuJpXCYCuPzxGL_z4HHz-7go2nlBB4HrnL7CoDA.eEOu1PwmmsQFvbwK67yBEA.SWecjp-pSsgY3-hvtezFGA.n5CtpyZ-GKBCxcL0uSpUlKlPdYpNBvrXEBEk7OX628Q'
```

Here's what happens when I add a "kid" to the encryption key:

```
>>> encryption_keys = [RSAKey(use="enc", key=RSA.generate(2048), kid="some-key-id")]
>>> jwe = JWE("some content", alg="RSA-OAEP", enc="A256CBC-HS512")
>>> jwe.encrypt(keys=encryption_keys, kid="some-key-id")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pyjwkest-1.0.1-py2.7.egg/jwkest/jwe.py", line 655, in encrypt
    raise NoSuitableEncryptionKey()
jwkest.jwe.NoSuitableEncryptionKey
```

It does seem possible to do this with symmetric encryption keys:

```
>>> symkey = {"kty":"oct","alg":"A128KW","k":"GawgguFyGrWKav7AX4VKUg","kid":"some-key-id"}
>>> k = KEYS()
>>> k.load_dict({"keys":[symkey]})
>>> jwe = JWE("some content", alg="A128KW", enc="A256CBC-HS512")
>>> jwe.encrypt(keys=k, kid="some-key-id")
'eyJhbGciOiJBMTI4S1ciLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwia2lkIjoic29tZS1rZXktaWQifQ.OIQzQZaIlR7vH6ZsZalefqk5fTh7j4wz4ypRj0dYTCiOVR6U7xwAdJGssKiEYntme6KyxBP6RB3CKJft3tqv0nLNMuP2WUfz.go8CePZYfQhRgVfbnBXKOw.wbPTCMZWRE14p1P1vS9fYQ.k3AsKWJ6pnrgFLFZAfL1pOLL7yPU53sMfZAFZPVAkqg'
```

**Comment by rohe** [comment]
> 22 jul 2015 kl. 00:08 skrev Arjun Sharma <notifications@github.com>:
> 
> When I follow the example code for creating a JWE, it does not work when I add a "kid" to the encryption key.
> 
> Here's what happens when I follow the example as written:
> 
> >>> encryption_keys = [RSAKey(use="enc", key=RSA.generate(2048))]
> >>> jwe = JWE("some content", alg="RSA-OAEP", enc="A256CBC-HS512")
> >>> jwe.encrypt(keys=encryption_keys)
> 'eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkEyNTZDQkMtSFM1MTIifQ.LnOxoMXW_W96Kg51ccpoMDTaHzL1Owky4JCo1zNzZSPZrKWSbil_4DEdOrGPE9Tv3TMNunfJnN0pcB5fu8zXCvoVVUHwshrgIA9mOlHkfkb-4Xq4jOFfemMTpuW-uJhL2wzXa2FvRv96ZpRTEZaC0iYcKJya9aJ0WZOm3hibj1xRJd-ORLEYEjNJco8o5EqGZj4mcT8OaODLvOuqEuq3Bc01S8OORZ5MjUWvjVkc0co5ZmnPyKXvsMhdaT60e2xAzcoQJblhuRJY0j85zqz9IIkufAVFdVieExK-zZRasZ9xvVleuJpXCYCuPzxGL_z4HHz-7go2nlBB4HrnL7CoDA.eEOu1PwmmsQFvbwK67yBEA.SWecjp-pSsgY3-hvtezFGA.n5CtpyZ-GKBCxcL0uSpUlKlPdYpNBvrXEBEk7OX628Q'
> 
> Here's what happens when I add a "kid" to the encryption key:
> 
> >>> encryption_keys = [RSAKey(use="enc", key=RSA.generate(2048), kid="some-key-id")]
> >>> jwe = JWE("some content", alg="RSA-OAEP", enc="A256CBC-HS512")
> >>> jwe.encrypt(keys=encryption_keys, kid="some-key-id")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Library/Python/2.7/site-packages/pyjwkest-1.0.1-py2.7.egg/jwkest/jwe.py", line 655, in encrypt
>     raise NoSuitableEncryptionKey()
> jwkest.jwe.NoSuitableEncryptionKey

Think I just pushed a patch that fixes this, please verify !

- Roland

”Capitalism is the extraordinary belief that the nastiest of men for the nastiest of motives will somehow work for the benefit of all" - John Maynard Keynes.

**Comment by arjunsharma** [comment]
Thanks! I'll try that out today and let you know if I run into any issues.

**Comment by arjunsharma** [comment]
When I pulled the latest code, I got errors while creating my JWS, which I do before I create the JWE. The JWS creation was working before. 

I was able to get everything working by taking only your latest commit (293c0a730ee7479ad602b662d4550322c3bc650c), but removing the commit before it (cd34339b7cc015b58e5cc0877ffafee95d05fd4b). Here's what happened with the latest version of pyjwkest:

```
keyset = {"keys": [
{
"alg": "RS512",
"kty":"RSA",
"d":"ckLyXxkbjC4szg8q8G0ERBZV-9CszeOxpRtx1KM9BLl0Do3li_Km2vvFvfXJ7MxQpiZ18pBoCcyYQEU262ym8wI22JWMPrZe24HCNxLxqzr_JEuBhpKFxQF6EFTSvJEJD1FkoTuCTvN0zD7YHGaJQG6JzVEuFUY3ewxjH0FYNa_ppTnPP3LC-T9u_GX9Yqyuw1KOYoHSzhWSWQOeAgs4dH9-iAxN1wdZ6eH1jFWAs43svk_rhwdgyJMlihFtV9MAInBlfi_Zu8wRVhVl5urkJrLf0tGFnMbnzb6dYSlUXxEYClpY12W7kXW9aePDqkCwI4oZyxmOmgq4hunKGR1dAQ",
"e":"AQAB",
"use":"sig",
"kid": "af22448d-4c7b-464d-b63a-f5bd90f6d7d1",
"n":"o9g8DpUwBW6B1qmcm-TfEh4rNX7n1t38jdo4Gkl_cI3q--7n0Blg0kN88LHZvyZjUB2NhBdFYNxMP8ucy0dOXvWGWzaPmGnq3DM__lN8P4WjD1cCTAVEYKawNBAmGKqrFj1SgpPNsSqiqK-ALM1w6mZ-QGimjOgwCyJy3l9lzZh5D8tKnS2t1pZgE0X5P7lZQWHYpHPqp4jKhETzrCpPGfv0Rl6nmmjp7NlRYBkWKf_HEKE333J6M039m2FbKgxrBg3zmYYpmHuMzVgxxb8LSiv5aqyeyJjxM-YDUAgNQBfKNhONqXyu9DqtSprNkw6sqmuxK0QUVrNYl3b03PgS5Q"
}
]
}
>>> from jwkest.jwk import KEYS
>>> keys = KEYS()
>>> keys.load_dict(keyset)
>>> jws = JWS("payload", alg="RS512")
>>> jws.sign_compact(keys=keys)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pyjwkest-1.0.2-py2.7.egg/jwkest/jws.py", line 481, in sign_compact
    sig = _signer.sign(_input, key.get_key(alg=_alg, private=True))
  File "/Library/Python/2.7/site-packages/pyjwkest-1.0.2-py2.7.egg/jwkest/jws.py", line 133, in sign
    return signer.sign(h)
  File "/Library/Python/2.7/site-packages/Crypto/Signature/PKCS1_v1_5.py", line 112, in sign
    m = self._key.decrypt(em)
  File "/Library/Python/2.7/site-packages/Crypto/PublicKey/RSA.py", line 174, in decrypt
    return pubkey.pubkey.decrypt(self, ciphertext)
  File "/Library/Python/2.7/site-packages/Crypto/PublicKey/pubkey.py", line 93, in decrypt
    plaintext=self._decrypt(ciphertext)
  File "/Library/Python/2.7/site-packages/Crypto/PublicKey/RSA.py", line 239, in _decrypt
    mp = self.key._decrypt(cp)
  File "/Library/Python/2.7/site-packages/Crypto/PublicKey/_slowmath.py", line 52, in _decrypt
    raise TypeError("No private key")
TypeError: No private key
```

**Comment by rohe** [comment]
Fixed !
Just pushed a patch.

> 22 jul 2015 kl. 23:37 skrev Arjun Sharma <notifications@github.com>:
> 
> keyset = {"keys": [
> {
> "alg": "RS512",
> "kty":"RSA",
> "d":"ckLyXxkbjC4szg8q8G0ERBZV-9CszeOxpRtx1KM9BLl0Do3li_Km2vvFvfXJ7MxQpiZ18pBoCcyYQEU262ym8wI22JWMPrZe24HCNxLxqzr_JEuBhpKFxQF6EFTSvJEJD1FkoTuCTvN0zD7YHGaJQG6JzVEuFUY3ewxjH0FYNa_ppTnPP3LC-T9u_GX9Yqyuw1KOYoHSzhWSWQOeAgs4dH9-iAxN1wdZ6eH1jFWAs43svk_rhwdgyJMlihFtV9MAInBlfi_Zu8wRVhVl5urkJrLf0tGFnMbnzb6dYSlUXxEYClpY12W7kXW9aePDqkCwI4oZyxmOmgq4hunKGR1dAQ",
> "e":"AQAB",
> "use":"sig",
> "kid": "af22448d-4c7b-464d-b63a-f5bd90f6d7d1",
> "n":"o9g8DpUwBW6B1qmcm-TfEh4rNX7n1t38jdo4Gkl_cI3q--7n0Blg0kN88LHZvyZjUB2NhBdFYNxMP8ucy0dOXvWGWzaPmGnq3DM__lN8P4WjD1cCTAVEYKawNBAmGKqrFj1SgpPNsSqiqK-ALM1w6mZ-QGimjOgwCyJy3l9lzZh5D8tKnS2t1pZgE0X5P7lZQWHYpHPqp4jKhETzrCpPGfv0Rl6nmmjp7NlRYBkWKf_HEKE333J6M039m2FbKgxrBg3zmYYpmHuMzVgxxb8LSiv5aqyeyJjxM-YDUAgNQBfKNhONqXyu9DqtSprNkw6sqmuxK0QUVrNYl3b03PgS5Q"
> }
> ]
> }
> >>> from jwkest.jwk import KEYS
> >>> keys = KEYS()
> >>> keys.load_dict(keyset)
> >>> jws = JWS("payload", alg="RS512")
> >>> jws.sign_compact(keys=keys)
> 

- Roland

”Capitalism is the extraordinary belief that the nastiest of men for the nastiest of motives will somehow work for the benefit of all" - John Maynard Keynes.

**Comment by arjunsharma** [comment]
Works great! Thanks again for all your help!
