### ISSUE TITLE
JWE ECDH-ES support/examples

### ISSUE THREAD

**Issue by drennalls** [rohe/pyjwkest#45]
Are the ECDH JWEs supported ?
I couldn't find any usage in the testcases, so based on https://github.com/rohe/pyjwkest/blob/master/doc/keys.rst and https://github.com/rohe/pyjwkest/blob/master/doc/encrypt.rst I tried this...

```
from jwkest.jwk import ECKey
from jwkest.jwe import JWE
key = ECKey(**{"kty":"EC",
               "crv":"P-256",
               "x":"MKBCTNIcKUSDii11ySs3526iDZ8AiTo7Tu6KPAqv7D4",
               "y":"4Etl6SRW2YiLUrN5vfvVHuhp7x8PxltmWWlbbM4IFyM",
               "d":"870MB6gfuTJ4HtUnUvYMyJpr5eUZNP4Bk43bVdj3eAE",
               "use":"enc",
               "kid":"1"})
msg = "Testing test 1 2 3.."
jwe = JWE(msg, alg="ECDH-ES", enc="A256GCM")
encrypted_content = jwe.encrypt([key])
```

..but that just resulted in a NotSupportedAlgorithm..

```
    encrypted_content = jwe.encrypt([key])
  File "/usr/lib/python2.7/site-packages/jwkest/jwe.py", line 631, in encrypt
    raise NotSupportedAlgorithm
jwkest.jwe.NotSupportedAlgorithm
```

I also tried manually using the jwkest.jwe.JWE_EC class calling enc_setup() after instantiating, but that didn't work out. There's no 'enc' attribute since the class doesn't declare the args list and enc_setup seems to be expecting an ECKey arg for `key` (to get key.crv), but then passes it to ecdh_derive_key which expects a tuple that you'd normally get from key.get_key() and not a ECKey object. 

So just wondering..  is there some sample usage elsewhere that I could reference or is it really not supported ?

**Comment by techguy613** [comment]
ECDH has been included for a little bit now. Have you checked the latest version of the library?
