### ISSUE TITLE
Alg is None in the headers even if one is provided

### ISSUE THREAD

**Issue by fgaudin** [rohe/pyjwkest#46]
Spotted this in 1.0.8 while using https://github.com/juanifioren/django-oidc-provider

if this code is valid to create a token https://github.com/juanifioren/django-oidc-provider/blob/v0.2.1/oidc_provider/lib/utils/token.py#L50 then there is a regression coming from https://github.com/rohe/pyjwkest/commit/3292070ff3bf3e1a4ca5915832d7cbf9c121a006

**Comment by rohe** [comment]
> 3 dec 2015 kl. 01:36 skrev Francois Gaudin <notifications@github.com>:
> 
> Spotted this in 1.0.8 while using https://github.com/juanifioren/django-oidc-provider
> 
> if this code is valid to create a token https://github.com/juanifioren/django-oidc-provider/blob/v0.2.1/oidc_provider/lib/utils/token.py#L50 then there is a regression coming from 3292070

This is fixed in the last version on github.
I will push a new version to pypi.

— Roland
'Look, that's why there's rules, understand? So that you think before you break ’em.’ - Terry Pratchett
