### ISSUE TITLE
Possibly use PyCryptodome instead of PyCrypto?

### ISSUE THREAD

**Issue by aarsan** [rohe/pyjwkest#47]
I am wondering if you could change your dependency from PyCrypto to PyCryptodome because PyCrypto does not have a Wheel package and has not had any recent developments. Certain systems I am attempting to install this package on cannot use external compilers. PyCryptodome seems to be fully compatible.

**Comment by rohe** [comment]
> 9 jan 2016 kl. 21:54 skrev Progger <notifications@github.com>:
> 
> I am wondering if you could change your dependency from PyCrypto to PyCryptodome because PyCrypto does not have a Wheel package and has not had any recent developments. Certain systems I am attempting to install this package on cannot use external compilers. PyCryptodome seems to be fully compatible.

If that is the case I will consider it.

— Roland

**Comment by aarsan** [comment]
Thank you!

**Comment by jdunck** [comment]
Suggest closing this as it appears that you now req pycryptodome
https://github.com/rohe/pyjwkest/blob/master/setup.py
