### ISSUE TITLE
Import error in jwkest.jwk

### ISSUE THREAD

**Issue by joshuabach** [rohe/pyjwkest#52]
## Problem

On my system the following import in [src/jwkest/jwk.py:13](https://github.com/rohe/pyjwkest/blob/1.1.0/src/jwkest/jwk.py#L13) failes:

``` python
   [...]
11 from Crypto.PublicKey import RSA
12 from Crypto.PublicKey.RSA import importKey
13 from Crypto.PublicKey.RSA import RsaKey    # <-- Thats the one
14 from Crypto.Util.asn1 import DerSequence
   [...]
```

with the error message:

``` python
>>> import jwkest.jwk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/jwkest/jwk.py", line 13, in <module>
    from Crypto.PublicKey.RSA import RsaKey
ImportError: cannot import name 'RsaKey'
```
## Workaround

The import does not seem to be used. When i remove the faulting line 13 (`from Crypto.PublicKey.RSA import RsaKey`) everything works fine.
## Software
- python 3.5.1
- pyjwkest 1.1.0
- pycrypto 2.6.1
- pycryptodome 3.3.1
- (everything from Archlinux stable)

**Comment by wojtek-fliposports** [comment]
+1

**Comment by rebeckag** [comment]
This is due to a conflict between the two crypto libraries, `pycrypto` and `pycryptodome`. So if possible make sure that only `pycryptodome` is installed in your environment.

**Comment by wojtek-fliposports** [comment]
This is problem with pyjwkest - still in development and it changes very often. Maybe freeze the version ?

**Comment by yakky** [comment]
The problem here is that pycrypto is used by fabric / paramiko, and this is causing a lot of issues. Python packaging does not provide much help in this case, but using pyjwkest in the same virtualenv as fabric it's a bit PITA

**Comment by rohe** [comment]
The usage of pycryptodomex as a requirement should fix this because it will get Cryptodome installed beside Crypto and not one on top of the other.

**Comment by yakky** [comment]
@rohe that would be great!
