### ISSUE TITLE
load_jwks_from_url missing?

### ISSUE THREAD

**Issue by protoforge** [rohe/pyjwkest#55]
I'm using Python3 and encountering this error in a library I depend on:

----> 1 from jwkest.jwk import load_jwks_from_url
ImportError: cannot import name 'load_jwks_from_url'

Has this been renamed or re-factored to a new class?

**Comment by rohe** [comment]
> 5 feb 2016 kl. 19:45 skrev protoforge <notifications@github.com>:
> 
> I'm using Python3 and encountering this error in a library I depend on:
> 
> ----> 1 from jwkest.jwk import load_jwks_from_url
> ImportError: cannot import name 'load_jwks_from_url'
> 
> Has this been renamed or re-factored to a new class?

re-factored into a class.

This probably gives you what you want now:

from jwkest.jwk import KEYS

k = KEYS().load_from_url(<url>)._keys

I could wrap that in a function with the old name.

**Comment by protoforge** [comment]
I'm not sure of the best approach...  This is the library I'm experimenting
with:

https://github.com/intelie/django-oidc-auth/blob/master/oidc_auth/models.py#L8

**Comment by rohe** [comment]
> 5 feb 2016 kl. 20:03 skrev protoforge <notifications@github.com>:
> 
> I'm not sure of the best approach... This is the library I'm experimenting
> with:
> 
> https://github.com/intelie/django-oidc-auth/blob/master/oidc_auth/models.py#L8

Looking at the above on github perhaps it’s easier if I re-implement it then
get them (and possibly others) to change.

**Comment by protoforge** [comment]
Well - do you know of an alternate django OIDC provider I should try?

**Comment by protoforge** [comment]
Also, it looks like some other legacy things in the repos here are still referencing it:

```
doc/examples.rst:    from jwkest.jwk import load_jwks_from_url
doc/examples.rst:    key_set = load_jwks_from_url("https://example.com/jwks.json")
doc/keys.rst:    from jwkest.jwk import load_jwks_from_url
doc/keys.rst:    key_set = load_jwks_from_url("https://example.com/jwks.json")
script/jwdecrypt.py:from jwkest.jwk import load_jwks_from_url, RSAKey
script/jwdecrypt.py:        keys = assign(load_jwks_from_url(lrequest, args.jwk_url))
script/jwenc.py:from jwkest.jwk import load_jwks_from_url, RSAKey
script/jwenc.py:        keys = load_jwks_from_url(args.jwk_url, {})
```

**Comment by rohe** [comment]
yeah, I saw that !

So’ll re-implement it.

**Comment by rohe** [comment]
New version on pypi with load_jwks_from_url reimplemented.

**Comment by rohe** [comment]
no !

**Comment by protoforge** [comment]
> no !

Ha.  I only asked because that other library doesn't seem to be actively maintained and isn't updated for python3

Thank you for the quick fix!
