### ISSUE TITLE
Build a docs page

### ISSUE THREAD

**Issue by lsmag** [rohe/pyjwkest#6]
Hi @rohe,

I'm currently working on both an OIDC implementation on OAuthlib and a client for Django. I'm starting to use this lib for the JWK/JWS part, but I'm mostly using your tests to understand how to use your lib.

What do you think of a proper documentation page? I can work on it, if you like.

**Comment by juanifioren** [comment]
Am trying to use this lib for an OIDC provider for Django, but am failing due to the lack of docs.

**Comment by rohe** [comment]
> 6 mar 2015 kl. 07:29 skrev Juan Ignacio Fiorentino <notifications@github.com>:
> 
> Am trying to use this lib for an OIDC provider for Django, but am failing due to the lack of docs.

So, you’re trying to build a OpenID Connect provider in Django.
Unfortunately I don’t know a lot about Django so I wouldn’t know where to start.

Would you be interested in working with one of my guys on this.

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by juanifioren** [comment]
Thanks for the answer Roland,

The provider is already functional ([see project here](https://github.com/juanifioren/django-oidc-provider)), but I'm a little confused about how ID TOKEN must be signed and then encrypted.

Actually am using [PyJWT](https://github.com/jpadilla/pyjwt). Just doing:
```python
id_token_hash = jwt.encode(id_token_dic, client_secret)
```
Where `id_token_dic` contains some claims that are used within the ID Token (iss, sub, aud, etc.).

Actually is signed using `HS256`. Is this bad? Should at least implement `RS256`?. Maybe I misunderstood something about encryption.

_-- Ignacio_
