### ISSUE TITLE
Cryptodome breaks projects where pycrypto is used

### ISSUE THREAD

**Issue by yakky** [rohe/pyjwkest#60]
How about moving to cryptodomex which uses a different namespace and allows cryptodomex and pycrypto to cohesist?

**Comment by yakky** [comment]
Ah, I see that 8a757f78b9f49ec6e20bc82ebc42fe98b5e9e801 fixes this. How about a new release to pypi?

**Comment by rohe** [comment]
Yeah, it’s about time !

4 juni 2016 kl. 10:11 skrev Iacopo Spalletti <notifications@github.com<mailto:notifications@github.com>>:


Ah, I see that 8a757f7<https://github.com/rohe/pyjwkest/commit/8a757f78b9f49ec6e20bc82ebc42fe98b5e9e801> fixes this. How about a new release to pypi?

**Comment by yakky** [comment]
That would be great, thanks

**Comment by allardhoeve** [comment]
Yes, please release a new version. And tag it ;)

**Comment by yakky** [comment]
@rohe any news for the new release?

**Comment by rohe** [comment]
I released a new version June 7th.

26 juni 2016 kl. 17:26 skrev Iacopo Spalletti <notifications@github.com<mailto:notifications@github.com>>:


@rohe<https://github.com/rohe> any news for the new release?

**Comment by yakky** [comment]
@rohe Sorry, I only checked the github releases instead of pypi. Cosing this, thanks
