### ISSUE TITLE
Thoughts about storing CEK for later retrieval?

### ISSUE THREAD

**Issue by techguy613** [rohe/pyjwkest#63]
Hey all,

I'm working on a Flask-JWE module that allows Flask [http://flask.pocoo.org] to accept and return JWE messages. I'm running into an issue with with RSA-ES two-way communication. ECDH-ES allows for two-way communication, but RSA-ES transfers the CEK only in one direction. 

**One option** to allow this to work is to use the **same CEK** in the response, but use a different IV and change the `alg` to None in the response. 

The issue here is that, the way pyjwkest is implemented, the CEK is obscured to the JWE class and even then the JWE class maintains a function-scoped encryptor / decrypter variable that makes the CEK even less accessible.

I'm thinking about adding a set_cek() and get_cek() into JWe and JWE such that the individual subclasses of JWe can call set_cek() and such that get_cek() can be called on both JWe (subclasses) and JWE objects. Additionally, this may require the encrpyer/decrypter in JWE to be held as an object-scoped variable instead of a function-scoped variable.

Does anyone have any thought one way or another on this?

Thanks,

-- Matt

**Comment by techguy613** [comment]
Hey all, any thoughts about this?

**Comment by rohe** [comment]
> 26 juli 2016 kl. 01:40 skrev Matt David <notifications@github.com>:
> 
> Hey all, any thoughts about this?
> 

Sorry I’m on vacation so slow in responding.

Your proposal makes sense to me but I’m not going to do anything with it until and of this month.
If on the other hand you want to go ahead and provided a pull request please do so.

— Roland

**Comment by techguy613** [comment]
Thanks for merging the PR @rohe!
