### ISSUE TITLE
Unmaintained dependency - pycrypto

### ISSUE THREAD

**Issue by CrowbarKZ** [rohe/pyjwkest#66]
pycrypto package has not been maintained for at least two years judging by it's repo https://github.com/dlitz/pycrypto.
Also people reported vulnerabilities, e.g. https://github.com/dlitz/pycrypto/issues/176

Consider swapping to a fork/something else? People suggested pycryptodome(https://pycryptodome.readthedocs.io/en/latest/) as a drop-in replacement

**Comment by Allu2** [comment]
Judging by commit log, hasn't the project already done that move some month ago? 
https://github.com/rohe/pyjwkest/commit/8a757f78b9f49ec6e20bc82ebc42fe98b5e9e801

**Comment by CrowbarKZ** [comment]
uh my bad, I didn't take a look at setup.py, was referring to https://github.com/rohe/pyjwkest/blob/master/requirements.txt
