### ISSUE TITLE
tag releases on github

### ISSUE THREAD

**Issue by ignatenkobrain** [rohe/pyjwkest#68]
it would simplify packaging for distros.

Thanks!

**Comment by rohe** [comment]
Tagged new release.

**Comment by MeggyCal** [comment]
+1 for this issue

**Comment by rohe** [comment]
Note that nothing has happened with pyjwkest for quite some time now.
All new work is going on here: https://github.com/IdentityPython/JWTConnect-Python-CryptoJWT

**Comment by MeggyCal** [comment]
Thanks a lot for pointing out :)

**Comment by rohe** [comment]
You're welcome :-)
