### ISSUE TITLE
add jwk_from_dict?

### ISSUE THREAD

**Issue by jschlyter** [rohe/pyjwkest#70]
In our jwkest wrapper, we've defined a jwk_from_dict to build a jwk from a dictionary. Would it make sense to add to jwkest directly? If so, I'd be happy to provide a PR with code.

**Comment by rohe** [comment]
> 19 sep. 2016 kl. 09:03 skrev Jakob Schlyter <notifications@github.com>:
> 
> In our jwkest wrapper, we've defined a jwk_from_dict to build a jwk from a dictionary. Would it make sense to add to jwkest directly? If so, I'd be happy to provide a PR with code.
> 
> 
Please do !

**Comment by jschlyter** [comment]
Submitted as PR #71.
