### ISSUE TITLE
Please release current version to pypy

### ISSUE THREAD

**Issue by pjsg** [rohe/pyjwkest#72]
Hi -- please release the version that depends on pycryptodomex to pypy -- this will solve some nasty deployment issues. The current 1.1.7 version does not include the pycryptodomex change and hance cannot be installed with any other package that requires pycrypto.

**Comment by techguy613** [comment]
Looks like pyjwkest@1.3.1 was released on 5-Oct.

**Comment by rohe** [comment]
Done, 1.4.0 is out the door.
